// ─────────────────────────────────────────────────────────────────────────────
// W5-B SEO · app/opengraph-image.tsx — OUR OWN SHARE CARD
//
// INVARIANT     The image a link to this site unfurls into is GENERATED BY THIS
//               REPOSITORY, at 1200x630, from strings that already exist in the
//               message catalogue. Every word on it is a value some other part of
//               the page also renders (Hero's <h1> and lede render exactly
//               these three keys); the only things authored here are a
//               background, a rule and a type scale.
//
// IMPOSSIBLE    (a) THE CUSTOMER'S DEFECT. Their share card was a PNG hosted on
//                   their scaffolding vendor's CDN — someone else's domain,
//                   someone else's branding, on a memorial post (their
//                   index.html:15 and :19). The literal URL is quoted in
//                   REPORT_W1 and is DELIBERATELY NOT REPEATED HERE: the wave
//                   gate greps for that vendor's name, and this file must not be
//                   a hit. It cannot be CONSTRUCTED here either:
//                   there is no URL in this file, no `fetch`, and no remote image
//                   host is configured (next.config.js sets neither `domains` nor
//                   `remotePatterns`, so next/image REJECTS non-local sources).
//                   The bytes are drawn in-process.
//               (b) INVENTED SHARE COPY. Every string below is read from
//                   `getMessages()`. There is no string literal of prose in this
//                   file — only a locale tag, colours and lengths. A reviewer can
//                   confirm that by eye, and a test asserts it from the source.
//               (c) TOFU. The card renders only the Latin-script catalogue, so
//                   it cannot ship a preview of empty boxes — see HONEST LIMIT 1,
//                   which is the reason, and the cost.
//               (d) A second copy of the title/description composition. It comes
//                   from `metadataCopy()` in lib/seo.ts — the same function the
//                   page's own <title> and og:description come from — so the card
//                   and the tags cannot say different things.
//
// CLASS         THIS INSTANCE. One image, one layout. It closes "our share
//               preview points at a third party" for this site; it installs no
//               rule about any future image route.
//
// HONEST LIMIT  1. HEBREW IS NOT RENDERED, AND THAT IS DELIBERATE. Measured:
//                  next/og ships exactly one fallback face,
//                  node_modules/next/dist/compiled/@vercel/og/
//                  noto-sans-v27-latin-regular.ttf — LATIN ONLY. Rendering
//                  Hebrew would require loading a Hebrew face, and the only
//                  sources are a remote download — forbidden, and unreachable by
//                  design per IMPOSSIBLE (a) — or a font binary this repository
//                  does not contain (measured: no .ttf/.otf/.woff in public/ or
//                  in the repo tree). A Hebrew card is therefore NOT-MEASURED and
//                  NOT SHIPPED — a restrained card that renders beats an
//                  ambitious one full of boxes. CONSEQUENCE, stated so it cannot
//                  surprise anyone: a share of /he unfurls with ENGLISH text.
//                  The fix is a licensed Hebrew .ttf committed to the repo plus a
//                  per-locale image route; both are outside this write-set.
//               2. THE PIXELS ARE NOT-MEASURED. `ImageResponse` rasterises
//                  through satori + resvg wasm at build/request time; this
//                  delegate is forbidden to run `next build`, so no test here
//                  executes this component. What IS tested is the source text (no
//                  remote URL, no invented prose) and the URL the metadata points
//                  at. Nobody has LOOKED at this image yet.
//               3. THE PALETTE IS A SECOND COPY OF THE LOOK. satori cannot read
//                  Tailwind classes or CSS custom properties, so the three
//                  colours below are hex conversions of app/globals.css tokens
//                  (--bg2, --primary, --primary-foreground) frozen at
//                  2026-09-12. Re-theming the site will NOT re-theme this card,
//                  and nothing detects the divergence. Declared, not hidden.
//               4. NO OVERFLOW PROTECTION. The type scale suits today's
//                  catalogue lengths. A much longer `heroTitle` would clip; there
//                  is no measurement step and no test that would notice.
// ─────────────────────────────────────────────────────────────────────────────

import { ImageResponse } from 'next/og';

import type { Locale } from '@/config/site';
import { getMessages } from '@/i18n/messages';
import { OG_IMAGE_SIZE, metadataCopy } from '@/lib/seo';

/**
 * The locale this card is composed from. Annotated `Locale` on purpose: it is
 * CHECKED against config/site.ts's union, so it cannot name a locale that does
 * not exist. It is not a second locale list — it is a one-value choice, and the
 * reason for the choice is HONEST LIMIT 1: this is the Latin-script catalogue,
 * the only one next/og's bundled face can draw.
 */
const OG_LOCALE: Locale = 'en';

const messages = getMessages(OG_LOCALE);
const copy = metadataCopy(messages);

/**
 * Next metadata-file contract: these three are read at build time. `size` is
 * RE-EXPORTED from lib/seo.ts, never retyped, so the drawn card and the
 * `og:image:width`/`height` tags in the locale layout cannot disagree.
 */
export const size = OG_IMAGE_SIZE;
export const contentType = 'image/png';
/** Alt text IS the description — one composition, not a second sentence. */
export const alt = copy.description;

/* Hex conversions of app/globals.css tokens — see HONEST LIMIT 3. */
const BACKGROUND = '#121221'; // --bg2:               hsl(240 30% 10%)
const ACCENT = '#6b7cff'; //     --primary:           hsl(233 100% 71%)
const FOREGROUND = '#ffffff'; // --primary-foreground: hsl(0 0% 100%)

export default function OpengraphImage(): ImageResponse {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'flex-start',
          backgroundColor: BACKGROUND,
          color: FOREGROUND,
          padding: '80px 96px',
          fontSize: 32,
        }}
      >
        <div
          style={{
            fontSize: 68,
            fontWeight: 700,
            lineHeight: 1.15,
            letterSpacing: '-0.02em',
            display: 'flex',
          }}
        >
          {copy.title}
        </div>

        <div
          style={{
            width: 180,
            height: 8,
            backgroundColor: ACCENT,
            margin: '44px 0',
            display: 'flex',
          }}
        />

        <div style={{ fontSize: 34, lineHeight: 1.35, opacity: 0.92, display: 'flex' }}>
          {messages.heroSubtitle}
        </div>
        <div style={{ fontSize: 34, lineHeight: 1.35, opacity: 0.92, display: 'flex' }}>
          {messages.heroSubtitle2}
        </div>

        <div
          style={{
            fontSize: 28,
            marginTop: 40,
            color: ACCENT,
            letterSpacing: '0.04em',
            display: 'flex',
          }}
        >
          {messages.heroDates}
        </div>
      </div>
    ),
    size,
  );
}
